name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
        with:
          cache-disabled: true

      - name: Build Android SDK & Sample App
        working-directory: android
        run: ./gradlew :opencredential-sdk:assembleRelease :sample-app:assembleDebug

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build iOS SDK
        run: xcodebuild -scheme OpenCredentialSDK -destination 'generic/platform=iOS' build
